#include <Servo.h>
Servo ServoBase;
Servo ServoBrazo;
int EjeBase = 90;
int EjeBrazo = 30;
byte PosicionEje;
int PasosServo = 15;
int LedEstado = 7;

void setup() {
  Serial.begin(9600);
  ServoBase.attach(3);
  ServoBrazo.attach(5);
  ServoBase.write(EjeBase);
  ServoBrazo.write(EjeBrazo);
  pinMode(LedEstado, OUTPUT);
  digitalWrite(LedEstado, HIGH);
}

void loop() {
  if (Serial.available()) {
    PosicionEje = Serial.read();
    if (PosicionEje == 'W') { 
      EjeBrazo += PasosServo;
      ServoBrazo.write(EjeBrazo);
    } else if (PosicionEje == 'S') {
      EjeBrazo -= PasosServo;
      ServoBrazo.write(EjeBrazo);
    } else if (PosicionEje == 'A') {
      EjeBase += PasosServo;
      ServoBase.write(EjeBase);
    } else if (PosicionEje == 'D') {
      EjeBase -= PasosServo;
      ServoBase.write(EjeBase);
    } else if (PosicionEje == 'R') {
      ServoBase.write(90);
      ServoBrazo.write(30);
    }
    if (PosicionEje == 'P') {
      ServoBase.write(90);
      ServoBrazo.write(30);
      digitalWrite(LedEstado, LOW);
      delay(1000);
      digitalWrite(LedEstado, HIGH);
      delay(1000);
      ServoBase.write(85);
      delay(50);
      ServoBase.write(80);
      delay(50);
      ServoBase.write(75);
      delay(50);
      ServoBase.write(70);
      delay(50);
      ServoBase.write(65);
      delay(250);
      ServoBrazo.write(25);
      delay(50);
      ServoBrazo.write(20);
      delay(50);
      ServoBrazo.write(15);
      delay(50);
      ServoBrazo.write(10);
      delay(250);
      ServoBase.write(70);
      delay(50);
      ServoBase.write(75);
      delay(50);
      ServoBase.write(80);
      delay(50);
      ServoBase.write(85);
      delay(50);
      ServoBase.write(90);
      delay(50);
      ServoBase.write(95);
      delay(250);
      ServoBrazo.write(15);
      delay(50);
      ServoBrazo.write(20);
      delay(50);
      ServoBrazo.write(25);
      delay(50);
      ServoBrazo.write(30);
      delay(50);
      ServoBrazo.write(35);
      delay(50);
      ServoBrazo.write(40);
      delay(50);
      ServoBrazo.write(45);
      delay(50);
      ServoBrazo.write(50);
      delay(50);
      ServoBrazo.write(55);
      delay(50);
      ServoBrazo.write(60);
      delay(50);
      ServoBrazo.write(65);
      delay(50);
      ServoBrazo.write(70);
      delay(250);
      ServoBase.write(95);
      delay(50);
      ServoBase.write(100);
      delay(50);
      ServoBase.write(105);
      delay(50);
      ServoBase.write(110);
      delay(50);
      ServoBase.write(115);
      delay(50);
      ServoBase.write(120);
      delay(50);
      ServoBase.write(125);
      delay(50);
      ServoBase.write(130);
      delay(50);
      ServoBase.write(135);
      delay(50);
      ServoBase.write(140);
      delay(50);
      ServoBase.write(145);
      delay(50);
      ServoBase.write(150);
      delay(50);
      ServoBase.write(155);
      delay(50);
      ServoBase.write(160);
      delay(50);
      ServoBase.write(165);
      delay(50);
      ServoBase.write(170);
      delay(50);
      ServoBase.write(175);
      delay(50);
      ServoBase.write(180);
      delay(250);
      digitalWrite(LedEstado, LOW);
      delay(500);
      digitalWrite(LedEstado, HIGH);
      delay(500);
      digitalWrite(LedEstado, LOW);
      delay(500);
      digitalWrite(LedEstado, HIGH);
      delay(500);
      digitalWrite(LedEstado, LOW);
      delay(500);
      digitalWrite(LedEstado, HIGH);
      delay(250);
      ServoBrazo.write(65);
      delay(50);
      ServoBrazo.write(60);
      delay(50);
      ServoBrazo.write(55);
      delay(50);
      ServoBrazo.write(50);
      delay(50);
      ServoBrazo.write(45);
      delay(50);
      ServoBrazo.write(40);
      delay(50);
      ServoBrazo.write(35);
      delay(50);
      ServoBrazo.write(30);
      delay(50);
      ServoBrazo.write(25);
      delay(50);
      ServoBrazo.write(20);
      delay(50);
      ServoBrazo.write(15);
      delay(50);
      ServoBrazo.write(10);
      delay(250);
      digitalWrite(LedEstado, LOW);
      delay(500);
      digitalWrite(LedEstado, HIGH);
      delay(500);
      digitalWrite(LedEstado, LOW);
      delay(500);
      digitalWrite(LedEstado, HIGH);
      delay(500);
      digitalWrite(LedEstado, LOW);
      delay(500);
      digitalWrite(LedEstado, HIGH);
      delay(250);
      ServoBase.write(175);
      delay(50);
      ServoBase.write(170);
      delay(50);
      ServoBase.write(165);
      delay(50);
      ServoBase.write(160);
      delay(50);
      ServoBase.write(155);
      delay(50);
      ServoBase.write(150);
      delay(50);
      ServoBase.write(145);
      delay(50);
      ServoBase.write(140);
      delay(50);
      ServoBase.write(135);
      delay(50);
      ServoBase.write(130);
      delay(50);
      ServoBase.write(125);
      delay(50);
      ServoBase.write(120);
      delay(50);
      ServoBase.write(115);
      delay(50);
      ServoBase.write(110);
      delay(50);
      ServoBase.write(105);
      delay(50);
      ServoBase.write(100);
      delay(50);
      ServoBase.write(95);
      delay(50);
      ServoBase.write(90);
      delay(250);
      ServoBrazo.write(15);
      delay(50);
      ServoBrazo.write(20);
      delay(50);
      ServoBrazo.write(25);
      delay(50);
      ServoBrazo.write(30);
      delay(250);
      digitalWrite(LedEstado, LOW);
      delay(500);
      digitalWrite(LedEstado, HIGH);
      delay(500);
      digitalWrite(LedEstado, LOW);
      delay(500);
      digitalWrite(LedEstado, HIGH);
      delay(500);
      digitalWrite(LedEstado, LOW);
      delay(500);
      digitalWrite(LedEstado, HIGH);
    }
  }
}
