#include <Servo.h>
Servo ServoBase;
Servo ServoBrazo;
int EjeBase = 90;
int EjeBrazo = 30;
byte Dato;
int PasosServo = 10;
int LedEstado = 7;
int LedLinternaUno = 9;
int LedLinternaDos = 10;
int AlarmaEmergencia = 12;

void setup() {
  Serial.begin(9600);
  ServoBase.attach(3);
  ServoBrazo.attach(5);
  ServoBase.write(EjeBase);
  ServoBrazo.write(EjeBrazo);
  pinMode(LedEstado, OUTPUT);
  digitalWrite(LedEstado, HIGH);
  pinMode(LedLinternaUno, OUTPUT);
  pinMode(LedLinternaDos, OUTPUT);
  pinMode(AlarmaEmergencia, OUTPUT);
}

void loop() {
  if (Serial.available()) {
    Dato = Serial.read();
    if (Dato == 'W') {
      EjeBrazo += PasosServo;
      ServoBrazo.write(EjeBrazo);
      Serial.println(EjeBrazo);
    } else if (Dato == 'S') {
      EjeBrazo -= PasosServo;
      ServoBrazo.write(EjeBrazo);
      Serial.println(EjeBrazo);
    } else if (Dato == 'A') {
      EjeBase += PasosServo;
      ServoBase.write(EjeBase);
      Serial.println(EjeBase);
    } else if (Dato == 'D') {
      EjeBase -= PasosServo;
      ServoBase.write(EjeBase);
      Serial.println(EjeBase);
    } else if (Dato == 'R') {
      EjeBase = 90;
      EjeBrazo = 30;
      ServoBase.write(90);
      ServoBrazo.write(30);
      Serial.println(EjeBrazo);
      Serial.print(EjeBase);
    }
    if (Dato == 'P') {
      ServoBase.write(90);
      ServoBrazo.write(30);
      digitalWrite(LedEstado, LOW);
      delay(500);
      digitalWrite(LedEstado, HIGH);
      delay(500);
      digitalWrite(LedEstado, LOW);
      delay(500);
      digitalWrite(LedEstado, HIGH);
      delay(500);
      digitalWrite(LedEstado, LOW);
      delay(500);
      digitalWrite(LedEstado, HIGH);
      delay(1000);
      ServoBase.write(85);
      delay(50);
      ServoBase.write(80);
      delay(50);
      ServoBase.write(75);
      delay(50);
      ServoBase.write(70);
      delay(50);
      ServoBase.write(65);
      Serial.println(65);
      delay(250);
      ServoBrazo.write(25);
      delay(50);
      ServoBrazo.write(20);
      delay(50);
      ServoBrazo.write(15);
      delay(50);
      ServoBrazo.write(10);
      Serial.println(10);
      delay(250);
      ServoBase.write(70);
      delay(50);
      ServoBase.write(75);
      delay(50);
      ServoBase.write(80);
      delay(50);
      ServoBase.write(85);
      delay(50);
      ServoBase.write(90);
      delay(50);
      ServoBase.write(95);
      Serial.println(95);
      delay(250);
      ServoBrazo.write(15);
      delay(50);
      ServoBrazo.write(20);
      delay(50);
      ServoBrazo.write(25);
      delay(50);
      ServoBrazo.write(30);
      delay(50);
      ServoBrazo.write(35);
      delay(50);
      ServoBrazo.write(40);
      delay(50);
      ServoBrazo.write(45);
      delay(50);
      ServoBrazo.write(50);
      delay(50);
      ServoBrazo.write(55);
      delay(50);
      ServoBrazo.write(60);
      delay(50);
      ServoBrazo.write(65);
      delay(50);
      ServoBrazo.write(70);
      Serial.println(70);
      delay(250);
      ServoBase.write(95);
      delay(50);
      ServoBase.write(100);
      delay(50);
      ServoBase.write(105);
      delay(50);
      ServoBase.write(110);
      delay(50);
      ServoBase.write(115);
      delay(50);
      ServoBase.write(120);
      delay(50);
      ServoBase.write(125);
      delay(50);
      ServoBase.write(130);
      delay(50);
      ServoBase.write(135);
      delay(50);
      ServoBase.write(140);
      delay(50);
      ServoBase.write(145);
      delay(50);
      ServoBase.write(150);
      delay(50);
      ServoBase.write(155);
      delay(50);
      ServoBase.write(160);
      delay(50);
      ServoBase.write(165);
      delay(50);
      ServoBase.write(170);
      delay(50);
      ServoBase.write(175);
      delay(50);
      ServoBase.write(180);
      Serial.println(180);
      delay(250);
      ServoBrazo.write(65);
      delay(50);
      ServoBrazo.write(60);
      delay(50);
      ServoBrazo.write(55);
      delay(50);
      ServoBrazo.write(50);
      delay(50);
      ServoBrazo.write(45);
      delay(50);
      ServoBrazo.write(40);
      delay(50);
      ServoBrazo.write(35);
      delay(50);
      ServoBrazo.write(30);
      delay(50);
      ServoBrazo.write(25);
      delay(50);
      ServoBrazo.write(20);
      delay(50);
      ServoBrazo.write(15);
      delay(50);
      ServoBrazo.write(10);
      Serial.println(10);
      delay(250);
      ServoBase.write(175);
      delay(50);
      ServoBase.write(170);
      delay(50);
      ServoBase.write(165);
      delay(50);
      ServoBase.write(160);
      delay(50);
      ServoBase.write(155);
      delay(50);
      ServoBase.write(150);
      delay(50);
      ServoBase.write(145);
      delay(50);
      ServoBase.write(140);
      delay(50);
      ServoBase.write(135);
      delay(50);
      ServoBase.write(130);
      delay(50);
      ServoBase.write(125);
      delay(50);
      ServoBase.write(120);
      delay(50);
      ServoBase.write(115);
      delay(50);
      ServoBase.write(110);
      delay(50);
      ServoBase.write(105);
      delay(50);
      ServoBase.write(100);
      delay(50);
      ServoBase.write(95);
      delay(50);
      ServoBase.write(90);
      Serial.println(90);
      delay(250);
      ServoBrazo.write(15);
      delay(50);
      ServoBrazo.write(20);
      delay(50);
      ServoBrazo.write(25);
      delay(50);
      ServoBrazo.write(30);
      Serial.println(30);
    }
    if (Dato == 'O') {
      ServoBase.write(90);
      ServoBrazo.write(30);
      digitalWrite(LedEstado, LOW);
      delay(500);
      digitalWrite(LedEstado, HIGH);
      delay(500);
      digitalWrite(LedEstado, LOW);
      delay(500);
      digitalWrite(LedEstado, HIGH);
      delay(500);
      digitalWrite(LedEstado, LOW);
      delay(500);
      digitalWrite(LedEstado, HIGH);
      delay(1000);
      ServoBase.write(85);
      delay(50);
      ServoBase.write(80);
      delay(50);
      ServoBase.write(75);
      delay(50);
      ServoBase.write(70);
      delay(50);
      ServoBase.write(65);
      delay(50);
      ServoBase.write(60);
      delay(50);
      ServoBase.write(55);
      delay(50);
      ServoBase.write(50);
      delay(50);
      ServoBase.write(45);
      delay(50);
      ServoBase.write(40);
      delay(50);
      ServoBase.write(35);
      delay(50);
      ServoBase.write(30);
      delay(50);
      ServoBase.write(25);
      delay(50);
      ServoBase.write(20);
      delay(250);
      ServoBrazo.write(25);
      delay(50);
      ServoBrazo.write(20);
      delay(50);
      ServoBrazo.write(15);
      delay(250);
      ServoBase.write(35);
      delay(50);
      ServoBase.write(40);
      delay(50);
      ServoBase.write(45);
      delay(250);
      ServoBrazo.write(20);
      delay(50);
      ServoBrazo.write(25);
      delay(50);
      ServoBrazo.write(30);
      delay(50);
      ServoBrazo.write(35);
      delay(50);
      ServoBrazo.write(40);
      delay(50);
      ServoBrazo.write(45);
      delay(50);
      ServoBrazo.write(50);
      delay(50);
      ServoBrazo.write(55);
      delay(50);
      ServoBrazo.write(60);
      delay(50);
      ServoBrazo.write(65);
      delay(50);
      ServoBrazo.write(70);
      delay(250);
      ServoBase.write(50);
      delay(50);
      ServoBase.write(55);
      delay(50);
      ServoBase.write(60);
      delay(50);
      ServoBase.write(65);
      delay(50);
      ServoBase.write(70);
      delay(50);
      ServoBase.write(75);
      delay(50);
      ServoBase.write(80);
      delay(50);
      ServoBase.write(85);
      delay(50);
      ServoBase.write(90);
      delay(50);
      ServoBase.write(95);
      delay(50);
      ServoBase.write(100);
      delay(50);
      ServoBase.write(105);
      delay(50);
      ServoBase.write(110);
      delay(50);
      ServoBase.write(115);
      delay(50);
      ServoBase.write(120);
      delay(50);
      ServoBase.write(125);
      delay(50);
      ServoBase.write(130);
      delay(50);
      ServoBase.write(135);
      delay(50);
      ServoBase.write(140);
      delay(50);
      ServoBase.write(145);
      delay(50);
      ServoBase.write(150);
      delay(50);
      ServoBase.write(155);
      delay(50);
      ServoBase.write(160);
      delay(50);
      ServoBase.write(165);
      delay(50);
      ServoBase.write(170);
      delay(50);
      ServoBase.write(175);
      delay(50);
      ServoBase.write(180);
      delay(250);
      ServoBrazo.write(65);
      delay(50);
      ServoBrazo.write(60);
      delay(50);
      ServoBrazo.write(55);
      delay(50);
      ServoBrazo.write(50);
      delay(50);
      ServoBrazo.write(45);
      delay(50);
      ServoBrazo.write(40);
      delay(50);
      ServoBrazo.write(35);
      delay(250);
      digitalWrite(LedLinternaUno, HIGH);
      digitalWrite(LedLinternaDos, HIGH);
      delay(250);
      ServoBase.write(175);
      delay(50);
      ServoBase.write(170);
      delay(50);
      ServoBase.write(165);
      delay(50);
      ServoBase.write(160);
      delay(50);
      ServoBase.write(155);
      delay(50);
      ServoBase.write(150);
      delay(50);
      ServoBase.write(145);
      delay(50);
      ServoBase.write(140);
      delay(50);
      ServoBase.write(135);
      delay(50);
      ServoBase.write(130);
      delay(50);
      ServoBase.write(125);
      delay(50);
      ServoBase.write(120);
      delay(50);
      ServoBase.write(115);
      delay(50);
      ServoBase.write(110);
      delay(50);
      ServoBase.write(105);
      delay(50);
      ServoBase.write(100);
      delay(50);
      ServoBase.write(95);
      delay(50);
      ServoBase.write(90);
      delay(250);
      ServoBrazo.write(30);
      delay(50);
      ServoBrazo.write(25);
      delay(50);
      ServoBrazo.write(20);
      delay(250);
      ServoBase.write(85);
      delay(50);
      ServoBase.write(80);
      delay(50);
      ServoBase.write(75);
      delay(50);
      ServoBase.write(70);
      delay(250);
      ServoBrazo.write(30);
      delay(250);
      ServoBase.write(75);
      delay(50);
      ServoBase.write(80);
      delay(50);
      ServoBase.write(85);
      delay(50);
      ServoBase.write(90);
      delay(250);
      digitalWrite(LedLinternaUno, LOW);
      digitalWrite(LedLinternaDos, LOW);
    }
    if (Dato == 'Z') {
      digitalWrite(LedLinternaUno, HIGH);
      digitalWrite(LedLinternaDos, HIGH);
    } else if (Dato == 'X') {
      digitalWrite(LedLinternaUno, LOW);
      digitalWrite(LedLinternaDos, LOW);
    }
    if (Dato == 'E') {
      digitalWrite(LedEstado, LOW);
      delay(500);
      digitalWrite(LedEstado, HIGH);
      digitalWrite(AlarmaEmergencia, HIGH);
      delay(500);
      digitalWrite(LedEstado, LOW);
      digitalWrite(AlarmaEmergencia, LOW);
      delay(500);
      digitalWrite(LedEstado, HIGH);
      digitalWrite(AlarmaEmergencia, HIGH);
      delay(500);
      digitalWrite(LedEstado, LOW);
      digitalWrite(AlarmaEmergencia, LOW);
      delay(500);
      digitalWrite(LedEstado, HIGH);
      digitalWrite(AlarmaEmergencia, HIGH);
      delay(500);
      digitalWrite(LedEstado, LOW);
      digitalWrite(AlarmaEmergencia, LOW);
      delay(500);
      digitalWrite(LedEstado, HIGH);
      digitalWrite(AlarmaEmergencia, HIGH);
      delay(500);
      digitalWrite(LedEstado, LOW);
      digitalWrite(AlarmaEmergencia, LOW);
      delay(500);
      digitalWrite(LedEstado, HIGH);
      digitalWrite(AlarmaEmergencia, HIGH);
      delay(500);
      digitalWrite(AlarmaEmergencia, LOW);
    }
  }
}